# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_cloud.v1 import sandbox_pb2 as agent__cloud_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_cloud/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxStub:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecTool = channel.unary_unary(
                '/agent_cloud.v1.Sandbox/ExecTool',
                request_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.FromString,
                _registered_method=True)
        self.WriteBinary = channel.unary_unary(
                '/agent_cloud.v1.Sandbox/WriteBinary',
                request_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryResponse.FromString,
                _registered_method=True)
        self.ReadBinary = channel.unary_unary(
                '/agent_cloud.v1.Sandbox/ReadBinary',
                request_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryResponse.FromString,
                _registered_method=True)
        self.Terminal = channel.stream_stream(
                '/agent_cloud.v1.Sandbox/Terminal',
                request_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.TerminalClientMsg.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.TerminalServerMsg.FromString,
                _registered_method=True)


class SandboxServicer:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    def ExecTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteBinary(self, request, context):
        """二进制落盘(worker→sandbox):worker 原生工具(如图片生成)把下载的字节写进工作区。
        走独立 RPC 而非 ExecTool/write_file:bytes 字段不经 JSON/base64,落地即原始文件
        (write_file 是 write_text,塞二进制会损坏 + 让 /files/raw 的 MIME 探测失效)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBinary(self, request, context):
        """二进制读取(worker→sandbox):worker 原生工具(如图片编辑)把工作区里的图读出来喂给外部 API。
        走独立 RPC:bytes 字段不经 JSON/base64,与 WriteBinary 对称。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminal(self, request_iterator, context):
        """交互式终端:双向流。client 发 start(开 PTY)/input(键盘字节)/resize;
        server 回 output(PTY 原始字节,含 ANSI)/exit_code(shell 退出收尾)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecTool,
                    request_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.SerializeToString,
            ),
            'WriteBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBinary,
                    request_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryResponse.SerializeToString,
            ),
            'ReadBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBinary,
                    request_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryResponse.SerializeToString,
            ),
            'Terminal': grpc.stream_stream_rpc_method_handler(
                    servicer.Terminal,
                    request_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.TerminalClientMsg.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.TerminalServerMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_cloud.v1.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_cloud.v1.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    @staticmethod
    def ExecTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Sandbox/ExecTool',
            agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.SerializeToString,
            agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Sandbox/WriteBinary',
            agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryRequest.SerializeToString,
            agent__cloud_dot_v1_dot_sandbox__pb2.WriteBinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Sandbox/ReadBinary',
            agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryRequest.SerializeToString,
            agent__cloud_dot_v1_dot_sandbox__pb2.ReadBinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agent_cloud.v1.Sandbox/Terminal',
            agent__cloud_dot_v1_dot_sandbox__pb2.TerminalClientMsg.SerializeToString,
            agent__cloud_dot_v1_dot_sandbox__pb2.TerminalServerMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
