# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_cloud.v1 import sandbox_pb2 as agent__cloud_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_cloud/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxStub:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecTool = channel.unary_unary(
                '/agent_cloud.v1.Sandbox/ExecTool',
                request_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.FromString,
                _registered_method=True)


class SandboxServicer:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    def ExecTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecTool,
                    request_deserializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_cloud.v1.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_cloud.v1.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox:
    """沙箱:在工作目录里执行一次工具调用(worker→sandbox,信任边界)。
    """

    @staticmethod
    def ExecTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Sandbox/ExecTool',
            agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolRequest.SerializeToString,
            agent__cloud_dot_v1_dot_sandbox__pb2.ExecToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
