# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_cloud.v1 import worker_pb2 as agent__cloud_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_cloud/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub:
    """worker:跑一个回合(后端→worker)。一元 RunTurn + 流式 RunTurnStream。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTurn = channel.unary_unary(
                '/agent_cloud.v1.Worker/RunTurn',
                request_serializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnResponse.FromString,
                _registered_method=True)
        self.RunTurnStream = channel.unary_stream(
                '/agent_cloud.v1.Worker/RunTurnStream',
                request_serializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_worker__pb2.TurnEvent.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_unary(
                '/agent_cloud.v1.Worker/Summarize',
                request_serializer=agent__cloud_dot_v1_dot_worker__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_worker__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.ExtractMemory = channel.unary_unary(
                '/agent_cloud.v1.Worker/ExtractMemory',
                request_serializer=agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryResponse.FromString,
                _registered_method=True)
        self.GenerateTitle = channel.unary_unary(
                '/agent_cloud.v1.Worker/GenerateTitle',
                request_serializer=agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleRequest.SerializeToString,
                response_deserializer=agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleResponse.FromString,
                _registered_method=True)


class WorkerServicer:
    """worker:跑一个回合(后端→worker)。一元 RunTurn + 流式 RunTurnStream。
    """

    def RunTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTurnStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTurn,
                    request_deserializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnResponse.SerializeToString,
            ),
            'RunTurnStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTurnStream,
                    request_deserializer=agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_worker__pb2.TurnEvent.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=agent__cloud_dot_v1_dot_worker__pb2.SummarizeRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_worker__pb2.SummarizeResponse.SerializeToString,
            ),
            'ExtractMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractMemory,
                    request_deserializer=agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryResponse.SerializeToString,
            ),
            'GenerateTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTitle,
                    request_deserializer=agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleRequest.FromString,
                    response_serializer=agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_cloud.v1.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_cloud.v1.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """worker:跑一个回合(后端→worker)。一元 RunTurn + 流式 RunTurnStream。
    """

    @staticmethod
    def RunTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Worker/RunTurn',
            agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.SerializeToString,
            agent__cloud_dot_v1_dot_worker__pb2.RunTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTurnStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_cloud.v1.Worker/RunTurnStream',
            agent__cloud_dot_v1_dot_worker__pb2.RunTurnRequest.SerializeToString,
            agent__cloud_dot_v1_dot_worker__pb2.TurnEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Worker/Summarize',
            agent__cloud_dot_v1_dot_worker__pb2.SummarizeRequest.SerializeToString,
            agent__cloud_dot_v1_dot_worker__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Worker/ExtractMemory',
            agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryRequest.SerializeToString,
            agent__cloud_dot_v1_dot_worker__pb2.ExtractMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_cloud.v1.Worker/GenerateTitle',
            agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleRequest.SerializeToString,
            agent__cloud_dot_v1_dot_worker__pb2.GenerateTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
